language: php
dist: bionic

services:
  - docker

php:
  - 7.4

env:
  global:
    - DRUPAL_BASE_URL="https://127.0.0.1:49156"
  matrix:
   # - JOB=job:run-coding-standard-check
    - JOB=job:run-unit-test

install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - sudo apt update
  - sudo apt install docker-ce
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose --version
  - curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
  - composer install

before_script:
  - cp .travis/phpunit.xml web/core
  - ddev start -y

script:
  - vendor/bin/robo $JOB

